/**
 * Placeholder Service Worker registration.
 * Registers the SW if the browser supports it.
 * The actual SW file is generated by vite-plugin-pwa during build.
 */
export function registerServiceWorker(): void {
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", () => {
      navigator.serviceWorker
        .register("/sw.js")
        .then((registration) => {
          console.log("SW registered:", registration.scope);
        })
        .catch((error) => {
          console.log("SW registration failed:", error);
        });
    });
  }
}
