#ENC[AES256_GCM,data:EyjFZKUFA5w8UTW2+He7adQhsrqtljhOqryrw3v7OthodzzLkMgbY1vWK++4K04+9w==,iv:mvyI+qNucX3dWoyjtt+M+dUPpuXjwtihwwwdgUOaftE=,tag:0BLB9qByzWtZbGepatkRqA==,type:comment]
#ENC[AES256_GCM,data:FZ8Sad91y7D9MA0u8JlxGpHWJNBZb3Pu+YJ5wxD5IIGxDFubWr7ar/KHcZ3woS7+86g=,iv:wwaIaDU3T/xEEAO6VZIP59OSasSXUALyBXq5yfDXVu8=,tag:3y3gmrWC2qb3zqA/4PlDPA==,type:comment]
#ENC[AES256_GCM,data:/yGF7s+sgt4kbuekQEeiy7DSHKlDk1ycMXK9x7W6RsK4TTBAO9kMkTEQHu8=,iv:FuM+ZcnCzpiYCDy+bZ+uFst57pj0Fp3z2ftggCSssi8=,tag:pCDI4SMbOJNDPVR0FZyAYQ==,type:comment]
DATABASE_URL: ENC[AES256_GCM,data:aX3IrgVxzEaumGyLpG8rpzXehjNeKK5HiHtXouPWZIC6m6eehrsfPl/96kLIgi2PU2Q+JmDjYhuear2mt0VG37A+XLSLg+ku6vHY7NIg15+QK7IkklDPW8xVDT62vPHWSpfO/WCK4QTpHbmpBRr2oG2Vqw==,iv:idijNNmb67QHiaeAzbZWgL0puTpdru7k3kTjDEYyaqA=,tag:oHqJjoWml8wVy9aR21nVxQ==,type:str]
JWT_SECRET: ENC[AES256_GCM,data:Zor5fkzEdSkhrUWFI4rSAd2Yv5IHbVgtyOPQEU5tObNl2Elwu7K2Z1AqEWn/t30xQM+5jiF38+Z+2ETvT4GS,iv:ofyIgn43DAIBMVdvWNKVppV4QWFPQA7R1vBpiIX+kLs=,tag:gd4H/tj+bT65WXqYyCey/Q==,type:str]
REBRICKABLE_API_KEY: ENC[AES256_GCM,data:w/6KysA9XYCp+lM2smg/jDuarugl8VOPTYSLpW8hPrc=,iv:aBpvrvdypl2ST7XqCXtwHkjDYEpklJt4PLAtYzl8yMk=,tag:lGEt4dNzF9nBHGtFHPinaw==,type:str]
R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:wVxTvR5bw4c8/GrG8qKlkknDSya1wqhqiFoteMk3F6E=,iv:hIps7II/t35vjJRbum0+7oGyZv+x/yWj5Z9R2g52oR0=,tag:7ER+i1TE8G6+P/3YUF05yA==,type:str]
R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:S6Ov1EYKEwPZmUmvMw7RRJjAu9eiBWs6hIP+oRMPvndoa92UR6nt54x/CTMloRdoOSMQjM4Qza3AWZzl6O6A1A==,iv:b3X2wVP/sowAuO7su9bMlaemj+rnc58jGZw8jW+IOWI=,tag:BfKlzacZf2qvkeQqJ1tEzA==,type:str]
R2_ENDPOINT: ENC[AES256_GCM,data:Uu23yqBQpuEE979Nwz+4YKXmoX+3V1AD66KNJd3LI1qEm9iMdYLOwy3dxv7wpDWYAfcY5NgKcJ4fAzISricM7lI=,iv:bzy7C6XyzpyLrKMwPW51xbahwpp8AqWAlphKGv0P5VI=,tag:93QCS8unULe0yOO2+ZJcbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVzFvcFhoUCtnYWxwUXU4
            RXlNRzFTa1J0S0ZjYmZieis3NEhTejVjd2dRCnFqMFJqR1lRYitZVkR0NGFad09k
            UlNiWVRGeVp1RDVDdnFSblR1N2ovQmcKLS0tIEE5SU5NeXBJOFl0TTJ6Qm8zdWcr
            ZUJpQUhDRUt6Y2NsekZyUTVwRGJuMkkKQYWPglXYuEW08YXVz7p8EEbYcQkVXtNx
            vPyNIx4w0j+J8xfasWB+EmV4VyHc1Gr6SczGymCMHgXyrUkDYvv7Xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u72rz7msetm7a7jd09hxlujdkhvlsgch2d89cr4dn4hx64e5qalq2q8p4m
    lastmodified: "2026-09-02T06:46:30Z"
    mac: ENC[AES256_GCM,data:0JCOVJfT5dULd8jD13JHz1lTXMMtBOZLHBtdeOizRH2+iA2/V1FQqODIjknLNCQgkIFtsC0Wvidnq/boVmYyDyYGgaCpb0DQll0Bc35FAV4RFuQNPPHmMMVo2+jdLbuMXcW6hVCODoq/ZfnQLfJ1v2YTXKBCTSMBEkX9BZLmLCM=,iv:m/riZJI7UCp0zstrWc1FoeKU1NwNj7H0TuoAyV/HnpE=,tag:do77d2P/H7CeIWrTInhOZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
